name: Android Build Debug AcademIA

on:
  push:
    branches:
      - main # Déclenche le workflow à chaque push sur la branche 'main'

jobs:
  build_android:
    runs-on: ubuntu-latest # Exécute le job sur une machine virtuelle Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Clone le code du dépôt

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Utilise Node.js version 20

      - name: Install npm dependencies
        run: npm install # Installe les dépendances Node.js

      - name: Build web app
        run: npm run build # Construit l'application web React (crée le dossier 'dist')

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli # Installe l'outil CLI de Capacitor globalement

      - name: Sync Capacitor web assets to Android
        run: npx cap sync android # Copie les assets web dans le projet Android

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Distribution Java recommandée
          java-version: '17' # Version de Java (doit correspondre à compileSdkVersion dans build.gradle)

      - name: Build Android Debug APK
        run: cd android && ./gradlew assembleDebug # Construit l'APK de débogage

      - name: Find APK file
        id: find_apk
        run: |
          # Trouve le chemin de l'APK généré (pour le build de débogage)
          APK_PATH=$(find android/app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          echo "APK trouvé à : $APK_PATH"
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT # Rend le chemin de l'APK disponible pour les étapes suivantes

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk # Nom de l'artefact
          path: ${{ steps.find_apk.outputs.apk_path }} # Chemin de l'APK à uploader

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/heads/main') # Crée une release uniquement si le push est sur la branche 'main'
        with:
          files: ${{ steps.find_apk.outputs.apk_path }} # Attache l'APK à la release
          name: Debug Release ${{ github.ref_name }}-${{ github.run_number }} # Nom de la release (ex: Debug Release main-1)
          tag_name: debug-v${{ github.run_number }} # Nom du tag (ex: debug-v1, debug-v2)
          body: | # Description de la release
            Release APK Android de DÉBOGAGE automatisée.
            Ce fichier APK n'est PAS signé pour la publication sur les stores.
            Numéro de build: ${{ github.run_number }}
            Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Token fourni automatiquement par GitHub pour l'authentification
